apiVersion: apps/v1
kind: Deployment
metadata:
  name: career-service
  namespace: assessment-ms
  labels:
    app: career-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: career-service
  template:
    metadata:
      labels:
        app: career-service
    spec:
      containers:
        - name: career-service
          image: fatmasboui/career-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/career_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761/eureka/
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"

---
apiVersion: v1
kind: Service
metadata:
  name: career-service
  namespace: assessment-ms
spec:
  selector:
    app: career-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort